repos:
-   repo: local
    hooks:
    - id: prepare-commit-msg
      name: <0> Prepare-commit-msg
      entry: "/Users/shimon.ohayon/code/dotfiles/prepare-commit-msg"
      stages: [prepare-commit-msg]
      language: script

-   repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.3.2
    hooks:
    - id: terraform-fmt
      name: <1> Terraform Format
    - id: tflint
      name: <2> Terraform Lint

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
    - id: yamllint
      name: <3> Yaml Lint
      args: [-c=/Users/shimon.ohayon/code/dotfiles/.yamllint.yml]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
      name: <4> Trailing whitespace
    - id: end-of-file-fixer
      name: <5> End of file fixer
    - id: no-commit-to-branch
      name: <6> No commit to branch
      args: ['--pattern', '^(?!(SRE|N2EOS)-[0-9]+\/([a-zA-Z0-9]|-)+)']
