repos:
-   repo: local
    hooks:
    - id: prepare-commit-msg
      name: Prepare-commit-msg
      entry: "/Users/shimon.ohayon/code/dotfiles/prepare-commit-msg"
      stages: [prepare-commit-msg]
      language: script
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.50.1
    hooks:
    - id: golangci-lint
      name: Go Lang Lint
-   repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.3.2
    hooks:
    - id: terraform-fmt
      name: Terraform Format
    - id: tflint
      name: Terraform Lint

-   repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
    - id: yamllint
      name: Yaml Lint
      args: [-c=/Users/shimon.ohayon/code/dotfiles/.yamllint.yml]
-   repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.9.0
    hooks:
    -   id: shellcheck
-   repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.6.0-1
    hooks:
    - id: shfmt
      name: shfmt
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: check-json
      name: Check JSON
    - id: trailing-whitespace
      name: Trailing whitespace
    - id: end-of-file-fixer
      name: End of file fixer
    - id: no-commit-to-branch
      name: No commit to branch
      args: ['--pattern', '^(?!(SRE|N2EOS)-[0-9]+\/([a-zA-Z0-9]|-)+)']
